"""Added Users restart

Revision ID: 3242ce99a2bb
Revises: 1f52ddbdfba8
Create Date: 2023-02-15 14:03:39.360832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3242ce99a2bb'
down_revision = '1f52ddbdfba8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
