"""update ads

Revision ID: 3f2c5adba78e
Revises: 5dae4fcaea32
Create Date: 2023-02-15 18:09:10.417935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2c5adba78e'
down_revision = '5dae4fcaea32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('text', sa.Text(), nullable=False))
    op.drop_column('ads', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('ads', 'text')
    # ### end Alembic commands ###
